---
# tasks file for arillso.postfix

- name: add OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "vars/{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "vars/{{ ansible_distribution }}.yml"
    - "vars/{{ ansible_os_family }}.yml"
    - "vars/defaults.yml"
  tags:
    - configuration
    - packages

- name: Postfix installed
  become: true
  package:
    name: "{{ item }}"
  with_items: "{{ postfix_packages }}"
  tags:
    - packages

- name: update configuration file
  become: true
  template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: 0644
  notify:
    - postmap sasl_passwd
    - restart postfix
  tags:
    - configuration

- name: configure sasl username/password
  become: true
  template:
    src: sasl_passwd.j2
    dest: /etc/postfix/sasl_passwd
    owner: root
    group: root
    mode: 0600
  when: postfix_relayhost
  notify:
    - postmap sasl_passwd
    - restart postfix
  tags:
    - configuration

- name: configure aliases
  become: true
  lineinfile:
    dest: /etc/aliases
    regexp: '^[#]?root:'
    line: 'root:    {{ postfix_root_mailbox }}'
    owner: root
    group: root
    mode: 0644
  when: postfix_root_mailbox is defined
  notify:
    - new aliases
    - restart postfix
    - enabled postfix
  tags:
    - configuration
